### ISSUE TITLE
Git: allow either squashed commits or non-fast-forward merge, not both

### ISSUE THREAD

**Issue by kyptin** [RoleModel/BestPractices#19]
The `git/merge-strategy.md` document recommends squashing commits before merge, followed by a non-fast-forward (`--no-ff`) merge. This creates a redundant merge commit in the git history. If such a practice were followed, the git history would look like:

```
<squashed commit for feature A>
<empty merge commit for feature A>
<squashed commit for feature B>
<empty merge commit for feature B>
<squashed commit for hotfix H>
<empty merge commit for hotfix H>
<squashed commit for feature C>
<empty merge commit for feature C>
...
```

In asking RoleModel folks on Slack (just now), there seemed to be some agreement that this wasn't useful. I propose modifying the best practices to remove this redundancy. Specifically, I think squashed commits are fine, and non-fast-forward merges are ([mostly](http://endoflineblog.com/gitflow-considered-harmful)) fine, but using both for a given feature or hotfix should be considered an anti-pattern.

If this proposal is approved, I'm happy to make these changes. Just let me know.

**Comment by secoast00** [comment]
I agree, the history is much cleaner with single commits, no merge commit.

**Comment by kyptin** [comment]
Wow, I forgot about this issue! We're in the process of addressing this as part of #43, so I'm closing this as a duplicate. Thanks Kevin!
